[tox]
envlist = test, lint, security
skipsdist = True

[testenv]
basepython=python3.13
passenv = *
deps = -r {toxinidir}/requirements-dev.txt

[testenv:test]
description = Runs unit tests
commands =
    pytest infra/tests/ --cov=infra --cov-report=term-missing
    pytest backend/tests/ --cov=backend --cov-report=term-missing

[testenv:lint]
description = Runs linting and style checks
commands =
    flake8 infra/infra infra/tests
    flake8 backend
    black --check infra/infra infra/tests
    black --check backend/api backend/tests

[testenv:security]
description = Runs security checks
commands =
    bandit -r infra/infra -x infra/tests
    bandit -r backend/api -x backend/tests

# Needs more work. Don't know what I'm doing with these yet.
#    safety check infra/
#    safety check backend
