[tox]
envlist = infra, backend
skipsdist = True

[testenv]
basepython=python3.13
passenv = *

[testenv:backend]
description = Construct dev environment in backend/.venv
envdir = {toxinidir}/backend/.venv
deps = -r {toxinidir}/backend/requirements-dev.txt
setenv =
    PYTHONPATH = {toxinidir}/backend
commands =
    pytest backend/tests/ --cov=backend --cov-report=term-missing
    flake8 backend/api
    black --check backend/api backend/tests
    bandit -r backend/api -x backend/tests
    #safety check backend/api

[testenv:infra]
description = Construct dev environment in infra/.venv
envdir = {toxinidir}/infra/.venv
deps = -r {toxinidir}/infra/requirements-dev.txt
setenv =
    PYTHONPATH = {toxinidir}/infra
commands =
    pytest infra/tests/ --cov=infra --cov-report=term-missing
    flake8 infra/infra infra/tests
    black --check infra/infra infra/tests
    bandit -r infra/infra -x infra/tests
    #safety check infra/

